import {
  NextResponse,
} from "next/server";

import {
  handleUpload,
  type HandleUploadBody,
} from "@vercel/blob/client";

import {
  getAdminUser,
} from "@/lib/admin";

type UploadFolder =
  | "covers"
  | "gallery"
  | "motion"
  | "posters";

type ClientPayload = {
  folder?: UploadFolder;
};

const IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif",
];

const VIDEO_TYPES = [
  "video/mp4",
  "video/webm",
];

/* =====================================
   HELPERS
===================================== */

function isUploadFolder(
  value: unknown
): value is UploadFolder {
  return (
    typeof value ===
      "string" &&
    [
      "covers",
      "gallery",
      "motion",
      "posters",
    ].includes(value)
  );
}

function parseClientPayload(
  value:
    | string
    | null
    | undefined
): ClientPayload {
  if (!value) {
    return {};
  }

  try {
    const parsed =
      JSON.parse(
        value
      );

    if (
      typeof parsed ===
        "object" &&
      parsed !== null
    ) {
      return parsed as ClientPayload;
    }

    return {};
  } catch {
    return {};
  }
}

/* =====================================
   CLIENT UPLOAD HANDLER
===================================== */

export async function POST(
  request: Request
) {
  /* =====================================
     AUTHENTICATION
  ===================================== */

  const admin =
    await getAdminUser();

  if (!admin) {
    return NextResponse.json(
      {
        error:
          "You are not authorized to upload files.",
      },
      {
        status: 401,
      }
    );
  }

  try {
    const body =
      (await request.json()) as HandleUploadBody;

    const response =
      await handleUpload({
        body,

        request,

        /* =====================================
           AUTHORIZE UPLOAD
        ===================================== */

        onBeforeGenerateToken:
          async (
            pathname,
            clientPayload
          ) => {
            const payload =
              parseClientPayload(
                clientPayload
              );

            const folder =
              payload.folder;

            if (
              !isUploadFolder(
                folder
              )
            ) {
              throw new Error(
                "Invalid upload destination."
              );
            }

            /*
             * Extra protection:
             * the pathname generated by the client
             * must match the requested folder.
             */
            const expectedPrefix =
              `projects/${folder}/`;

            if (
              !pathname.startsWith(
                expectedPrefix
              )
            ) {
              throw new Error(
                "Upload path does not match the requested destination."
              );
            }

            /* =====================================
               MOTION VIDEO
            ===================================== */

            if (
              folder ===
              "motion"
            ) {
              return {
                allowedContentTypes:
                  VIDEO_TYPES,

                maximumSizeInBytes:
                  50 *
                  1024 *
                  1024,

                addRandomSuffix:
                  true,

                tokenPayload:
                  JSON.stringify({
                    folder,
                  }),
              };
            }

            /* =====================================
               IMAGE UPLOADS
            ===================================== */

            return {
              allowedContentTypes:
                IMAGE_TYPES,

              maximumSizeInBytes:
                10 *
                1024 *
                1024,

              addRandomSuffix:
                true,

              tokenPayload:
                JSON.stringify({
                  folder,
                }),
            };
          },

        /* =====================================
           UPLOAD COMPLETED
        ===================================== */

        onUploadCompleted:
          async ({
            blob,
            tokenPayload,
          }) => {
            /*
             * The ProjectForm will save blob.url
             * into Prisma when the project itself
             * is saved.
             *
             * Nothing needs to be written to the
             * database here.
             */

            console.log(
              "BLOB UPLOAD COMPLETED:",
              {
                pathname:
                  blob.pathname,

                url:
                  blob.url,

                tokenPayload,
              }
            );
          },
      });

    return NextResponse.json(
      response
    );
  } catch (error) {
    console.error(
      "PROJECT UPLOAD ERROR:",
      error
    );

    const details =
      error instanceof Error
        ? error.message
        : "Unknown upload error";

    return NextResponse.json(
      {
        error:
          "The file could not be uploaded.",

        details:
          process.env.NODE_ENV ===
          "development"
            ? details
            : undefined,
      },
      {
        status: 400,
      }
    );
  }
}